// SEO Course Data — all 11 landing pages
const courseData = {
  "icse-class-9-java-dehradun": {
    slug: "icse-class-9-java-dehradun",
    title: "ICSE Class 9 Java in Dehradun",
    metaTitle: "ICSE Class 9 Java Course in Dehradun | Codeware IT",
    metaDescription:
      "Best ICSE Class 9 Java coaching in Dehradun. Hands-on programming, syllabus-aligned curriculum, and expert faculty at Codeware IT Pvt Ltd.",
    keywords:
      "ICSE class 9 java dehradun, java class 9 ICSE coaching dehradun, class 9 java programming dehradun",
    heroTitle: "ICSE Class 9 Java",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Master Java fundamentals aligned with the ICSE Class 9 syllabus — loops, arrays, OOP basics, and more.",
    badge: "ICSE • Class 9",
    color: "#2563eb",
    icon: "☕",
    category: "ICSE",
    syllabus: [
      "Introduction to Java and Object-Oriented Programming",
      "Primitive Data Types, Variables & Operators",
      "Conditional Statements — if, if-else, switch",
      "Loops — for, while, do-while",
      "Arrays: Single and Double Dimensional",
      "String Handling — methods and manipulation",
      "Methods & Recursion basics",
      "ICSE Exam Practice Problems & Sample Papers",
    ],
    demoTopics: "Java Basics (OOP concepts, loops, arrays)",
    targetAudience: "Class 9 students following the ICSE board curriculum",
    duration: "3 Months",
    mode: "Offline / Online",
  },

  "icse-class-10-java-dehradun": {
    slug: "icse-class-10-java-dehradun",
    title: "ICSE Class 10 Java in Dehradun",
    metaTitle: "ICSE Class 10 Java Course in Dehradun | Codeware IT",
    metaDescription:
      "Top ICSE Class 10 Java institute in Dehradun. Board exam-oriented Java coaching with BlueJ, OOP, interfaces, and more at Codeware IT.",
    keywords:
      "ICSE class 10 java dehradun, java coaching class 10 dehradun, ICSE board java institute dehradun",
    heroTitle: "ICSE Class 10 Java",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Score full marks in Computer Applications. Board-exam focused Java coaching by experienced faculty.",
    badge: "ICSE • Class 10",
    color: "#1d4ed8",
    icon: "☕",
    category: "ICSE",
    syllabus: [
      "Classes, Objects & Constructors in Java",
      "Inheritance — Single & Multilevel",
      "Interfaces and Abstract Classes",
      "Exception Handling (try-catch-finally)",
      "String & StringBuilder Manipulation",
      "Sorting Algorithms — Bubble, Selection, Insertion",
      "Searching Algorithms — Linear & Binary Search",
      "BlueJ IDE — ICSE Board Paper Practice",
    ],
    demoTopics: "Java OOP — Inheritance, Interfaces, BlueJ practice",
    targetAudience: "ICSE Class 10 students preparing for board exams",
    duration: "3 Months",
    mode: "Offline / Online",
  },

  "cbse-class-11-python-dehradun": {
    slug: "cbse-class-11-python-dehradun",
    title: "CBSE Class 11 Python in Dehradun",
    metaTitle: "CBSE Class 11 Python Course in Dehradun | Codeware IT",
    metaDescription:
      "Best CBSE Class 11 Python coaching in Dehradun. Syllabus-aligned Python programming with Informatics Practices. Join Codeware IT Pvt Ltd.",
    keywords:
      "CBSE class 11 python dehradun, python class 11 coaching dehradun, informatics practices class 11 dehradun",
    heroTitle: "CBSE Class 11 Python",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Excel in Informatics Practices with CBSE-aligned Python coaching — from basics to data handling.",
    badge: "CBSE • Class 11",
    color: "#16a34a",
    icon: "🐍",
    category: "CBSE",
    syllabus: [
      "Introduction to Python — Syntax, Variables, Data Types",
      "Operators, Expressions and Input/Output",
      "Conditional Statements and Loops",
      "Functions and Recursion in Python",
      "Strings, Lists, Tuples, Dictionaries",
      "File Handling in Python",
      "Introduction to Pandas & Data Analysis",
      "CBSE Board Practice Questions & Lab Programs",
    ],
    demoTopics: "Python Fundamentals — Variables, Loops, Functions",
    targetAudience: "CBSE Class 11 students (Informatics Practices / CS)",
    duration: "4 Months",
    mode: "Offline / Online",
  },

  "cbse-class-12-python-dehradun": {
    slug: "cbse-class-12-python-dehradun",
    title: "CBSE Class 12 Python in Dehradun",
    metaTitle: "CBSE Class 12 Python Course in Dehradun | Codeware IT",
    metaDescription:
      "CBSE Class 12 Python coaching in Dehradun — SQL, File Handling, Data Visualization, Pandas. Score 95+ in Computer Science. Codeware IT Pvt Ltd.",
    keywords:
      "CBSE class 12 python dehradun, python class 12 coaching dehradun, class 12 computer science coaching dehradun",
    heroTitle: "CBSE Class 12 Python",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Board-focused Python coaching — SQL integration, data analysis, and practical lab programs to score 95+.",
    badge: "CBSE • Class 12",
    color: "#15803d",
    icon: "🐍",
    category: "CBSE",
    syllabus: [
      "Python Revision — OOP, Functions, Modules",
      "Stack and Queue using Python",
      "File Handling — Text and Binary Files",
      "Database Concepts & MySQL Integration with Python",
      "SQL Commands — DDL, DML, DQL",
      "Pandas — DataFrames, Data Analysis",
      "Data Visualization using Matplotlib",
      "CBSE Board Paper Solving & Practical Prep",
    ],
    demoTopics: "Python + SQL — File Handling, MySQL with Python",
    targetAudience: "CBSE Class 12 students (Computer Science / IP)",
    duration: "4 Months",
    mode: "Offline / Online",
  },

  "java-python-programming-dehradun": {
    slug: "java-python-programming-dehradun",
    title: "Java, Python, C, C++, C#, PHP for BCA / BSc IT / BTech / MCA",
    metaTitle:
      "Java Python C C++ PHP Course for BCA BSc BTech MCA in Dehradun | Codeware IT",
    metaDescription:
      "Best programming language courses in Dehradun for BCA, BSc IT, BTech, MCA students. Learn Java, Python, C, C++, C#, PHP with practical projects at Codeware IT.",
    keywords:
      "java python course dehradun, BCA programming course dehradun, BSc IT java python dehradun, BTech programming institute dehradun, MCA coaching dehradun, C C++ PHP course dehradun",
    heroTitle: "Programming Courses for Graduates",
    heroSubtitle: "Java · Python · C · C++ · C# · PHP",
    heroTagline:
      "Tailored for BCA, BSc IT, BTech & MCA students — master the languages your curriculum demands, with real projects.",
    badge: "Graduation Level",
    color: "#7c3aed",
    icon: "🎓",
    category: "Graduation",
    syllabus: [
      "Core Java — OOP, Collections, Exception Handling, JDBC",
      "Python — OOP, Django/Flask Basics, Data Libraries",
      "C Language — Pointers, Memory Management, File I/O",
      "C++ — STL, Templates, Multithreading",
      "C# — .NET Framework, Windows Forms Basics",
      "PHP — Server-Side Scripting, MySQL Integration",
      "University Exam Preparation & Lab Programs",
      "Mini Project Development & Viva Preparation",
    ],
    demoTopics: "Your choice of language — Java / Python / C / C++",
    targetAudience:
      "BCA, BSc IT, BTech, MCA students in Dehradun universities",
    duration: "3–6 Months (per language)",
    mode: "Offline / Online",
  },

  "web-development-course-dehradun": {
    slug: "web-development-course-dehradun",
    instructor: "Rahul Sharma — 8+ years web development & React experience",
    batchDate: "5 May 2025",
    seatsLeft: 9,
    testimonials: [
      { name: "Ritu Chauhan", role: "Web Developer, Dehradun Agency", text: "The web dev course at Codeware IT is the most practical I've seen. Got a job in 2 months!", rating: 5 },
      { name: "Saurabh Rawat", role: "Freelance Web Developer", text: "HTML, CSS, JavaScript, React — all in one course with real projects. Highly recommend!", rating: 5 },
      { name: "Pooja Bist", role: "BTech Student, GEU Dehradun", text: "Codeware IT made web development so easy to understand. Best institute in Dehradun!", rating: 5 },
    ],
    title: "Web Development Course in Dehradun",
    metaTitle: "Web Development Course in Dehradun | Codeware IT",
    metaDescription:
      "Join the best web development course in Dehradun at Codeware IT. Learn HTML, CSS, JavaScript, React, Node.js and build real projects. Job-ready training.",
    keywords:
      "web development course dehradun, web development institute dehradun, HTML CSS javascript course dehradun, best web development training dehradun",
    heroTitle: "Web Development Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "From zero to job-ready — build modern, responsive websites and web apps used by real users.",
    badge: "Job Ready",
    color: "#0891b2",
    icon: "🌐",
    category: "Job Ready",
    syllabus: [
      "HTML5 & CSS3 — Semantic Markup, Flexbox, Grid",
      "Responsive Design & Bootstrap / Tailwind CSS",
      "JavaScript ES6+ — DOM, Events, Fetch API",
      "React.js — Components, Hooks, State Management",
      "Node.js & Express.js — REST APIs",
      "MongoDB & Mongoose — Database Integration",
      "Authentication — JWT, Sessions",
      "Deployment — Vercel, Netlify, Render",
    ],
    demoTopics: "HTML + CSS + JavaScript basics — Build your first webpage",
    targetAudience: "Beginners, students, and career switchers",
    duration: "5 Months",
    mode: "Offline / Online",
  },

  "react-js-course-dehradun": {
    slug: "react-js-course-dehradun",
    instructor: "Rahul Sharma — 8+ years React.js & frontend development",
    batchDate: "5 May 2025",
    seatsLeft: 7,
    testimonials: [
      { name: "Sneha Rawat", role: "React Developer, Dehradun Startup", text: "The React JS course at Codeware IT is incredibly hands-on. Built 3 real apps and got placed!", rating: 5 },
      { name: "Mohit Bisht", role: "Frontend Intern, Remote", text: "Best React JS institute in Dehradun. Hooks, Redux, Router — all covered with real projects!", rating: 5 },
      { name: "Kavya Negi", role: "BCA Graduate, HNBGU", text: "From zero React to building full apps in 3 months. Codeware IT made the difference!", rating: 5 },
    ],
    title: "React JS Course in Dehradun",
    metaTitle: "React JS Course in Dehradun | Codeware IT",
    metaDescription:
      "Best React JS course in Dehradun at Codeware IT. Learn React Hooks, Redux, React Router, API integration and build real-world projects. Placement support.",
    keywords:
      "react js course dehradun, reactjs training dehradun, react js institute dehradun, learn react js dehradun",
    heroTitle: "React JS Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Master the most in-demand frontend library — build lightning-fast UIs for real-world apps.",
    badge: "Job Ready",
    color: "#0284c7",
    icon: "⚛️",
    category: "Job Ready",
    syllabus: [
      "JavaScript ES6+ Prerequisites — Arrow Functions, Destructuring",
      "React Fundamentals — JSX, Components, Props",
      "State Management with useState & useReducer",
      "Side Effects with useEffect — API Calls",
      "React Router v6 — SPA Navigation",
      "Context API & Redux Toolkit",
      "Form Handling & Validation",
      "Real-World Project — Full React App with API",
    ],
    demoTopics: "React Basics — Components, Props, State demo project",
    targetAudience: "Students knowing basic JavaScript who want frontend jobs",
    duration: "2 Months",
    mode: "Offline / Online",
  },

  "nextjs-course-dehradun": {
    slug: "nextjs-course-dehradun",
    instructor: "Rahul Sharma — 6+ years Next.js & full-stack React experience",
    batchDate: "5 May 2025",
    seatsLeft: 8,
    testimonials: [
      { name: "Abhishek Thakur", role: "Next.js Dev, Remote", text: "Codeware IT's Next.js course is industry-grade. SSR, SSG, API routes — all deeply covered!", rating: 5 },
      { name: "Isha Bisht", role: "Frontend Developer, Startup", text: "Finally understood the difference between React and Next.js. Excellent teaching!", rating: 5 },
      { name: "Tarun Rawat", role: "BTech CSE, Graphic Era", text: "The capstone project in this course is production-ready. Best Next.js training in Dehradun!", rating: 5 },
    ],
    title: "Next.js Course in Dehradun",
    metaTitle: "Next.js Course in Dehradun | Codeware IT",
    metaDescription:
      "Learn Next.js in Dehradun at Codeware IT — App Router, SSR, SSG, API Routes, SEO optimization. Build production-grade web apps. Placement support.",
    keywords:
      "nextjs course dehradun, next js training dehradun, next.js institute dehradun, learn nextjs dehradun",
    heroTitle: "Next.js Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "The React framework for production — SSR, SSG, API routes, and full-stack apps in one powerful course.",
    badge: "Job Ready",
    color: "#1e293b",
    icon: "▲",
    category: "Job Ready",
    syllabus: [
      "Next.js App Router — Pages, Layouts, Loading States",
      "Server Components vs Client Components",
      "Static Site Generation (SSG) & Incremental Static Regeneration",
      "Server-Side Rendering (SSR) with getServerSideProps",
      "API Routes & Route Handlers",
      "Database Integration — Prisma / MongoDB",
      "Authentication with NextAuth.js",
      "Deployment on Vercel — CI/CD Pipeline",
    ],
    demoTopics: "Next.js App Router — Pages, Routing, Server Components",
    targetAudience: "React developers ready to go full-stack",
    duration: "2 Months",
    mode: "Offline / Online",
  },

  "frontend-course-dehradun": {
    slug: "frontend-course-dehradun",
    title: "Frontend Development Course in Dehradun",
    metaTitle: "Frontend Development Course in Dehradun | Codeware IT",
    metaDescription:
      "Best frontend development course in Dehradun. Learn HTML, CSS, JavaScript, React, Tailwind and build stunning UIs. Codeware IT Pvt Ltd — job-ready training.",
    keywords:
      "frontend course dehradun, frontend development training dehradun, HTML CSS react course dehradun, UI development course dehradun",
    heroTitle: "Frontend Development Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Design and build beautiful, responsive user interfaces that users love — get hired as a frontend developer.",
    badge: "Job Ready",
    color: "#db2777",
    icon: "🎨",
    category: "Job Ready",
    syllabus: [
      "HTML5 — Semantic Tags, Accessibility, Forms",
      "Advanced CSS — Flexbox, Grid, Animations",
      "Responsive Design & Mobile-First Approach",
      "JavaScript — DOM Manipulation, ES6+, Fetch API",
      "Tailwind CSS & Component Libraries",
      "React.js — Hooks, State, Routing",
      "TypeScript Basics for Frontend",
      "Portfolio Project — Deploy a Professional Frontend",
    ],
    demoTopics: "HTML + CSS — Build a responsive landing page live",
    targetAudience: "Beginners wanting to become UI/Frontend developers",
    duration: "3 Months",
    mode: "Offline / Online",
  },

  "backend-course-dehradun": {
    slug: "backend-course-dehradun",
    title: "Backend Development Course in Dehradun",
    metaTitle: "Backend Development Course in Dehradun | Codeware IT",
    metaDescription:
      "Best backend development course in Dehradun at Codeware IT. Learn Node.js, Express, MongoDB, REST APIs, authentication and deploy scalable server apps.",
    keywords:
      "backend course dehradun, backend development training dehradun, nodejs express course dehradun, server side development dehradun",
    heroTitle: "Backend Development Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Power the web from the inside — build APIs, databases, and server logic that runs at scale.",
    badge: "Job Ready",
    color: "#b45309",
    icon: "⚙️",
    category: "Job Ready",
    syllabus: [
      "Node.js Fundamentals — Runtime, Modules, Event Loop",
      "Express.js — Routing, Middleware, Error Handling",
      "REST API Design — CRUD, Status Codes, Best Practices",
      "MongoDB & Mongoose — Schema Design, Queries",
      "Authentication — JWT, Bcrypt, Refresh Tokens",
      "File Uploads — Multer, Cloudinary",
      "Environment & Security — dotenv, CORS, Rate Limiting",
      "Deployment — Render, Railway, or AWS EC2",
    ],
    demoTopics: "Node.js + Express — Build a REST API live",
    targetAudience: "Students who want to specialize in server-side development",
    duration: "3 Months",
    mode: "Offline / Online",
  },

  "fullstack-course-dehradun": {
    slug: "fullstack-course-dehradun",
    title: "Full Stack Development Course in Dehradun",
    metaTitle: "Full Stack Development Course in Dehradun | Codeware IT",
    metaDescription:
      "Best full stack development course in Dehradun. Learn MERN Stack, React, Node.js, MongoDB, REST APIs at Codeware IT. Job placement support included.",
    keywords:
      "full stack course dehradun, fullstack development dehradun, MERN stack course dehradun, full stack training institute dehradun",
    heroTitle: "Full Stack Development Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "End-to-end mastery — build complete web applications from database to deployment, alone.",
    badge: "Job Ready",
    color: "#7c3aed",
    icon: "🚀",
    category: "Job Ready",
    syllabus: [
      "HTML, CSS, JavaScript & Responsive Design",
      "React.js — Components, Hooks, Redux",
      "Node.js & Express.js — REST APIs",
      "MongoDB & Mongoose — Full CRUD",
      "Authentication — JWT & Sessions",
      "Git & GitHub — Version Control Workflow",
      "Full-Stack Project — Build & Deploy End-to-End",
      "Interview Preparation & Resume Building",
    ],
    demoTopics: "Full stack mini app — React + Node + MongoDB demo",
    targetAudience: "Anyone aiming for a full-stack developer job",
    duration: "6 Months",
    mode: "Offline / Online",
  },


  // ─── 6 Google Ads Landing Pages (Task 2) ─────────────────────────────────

  "java-course-dehradun": {
    slug: "java-course-dehradun",
    title: "Java Course in Dehradun",
    metaTitle: "Best Java Course in Dehradun | Codeware IT",
    metaDescription:
      "Join the best Java course in Dehradun at Codeware IT. Learn OOP, data structures, Spring Boot & get placement support. Book FREE demo today!",
    keywords:
      "java course dehradun, java training dehradun, java institute dehradun, learn java dehradun, best java classes dehradun",
    heroTitle: "Best Java Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Master Java from basics to Spring Boot with real-world projects, small batches & guaranteed placement support at Dehradun's #1 coding institute.",
    badge: "🏆 Most Popular",
    color: "#ea580c",
    icon: "☕",
    category: "Job Ready",
    syllabus: [
      "Core Java — Syntax, Variables, Data Types, Operators",
      "Control Flow — if/else, switch, loops",
      "Object-Oriented Programming — Classes, Inheritance, Polymorphism",
      "Exception Handling & File I/O",
      "Collections Framework — List, Set, Map, Iterator",
      "Multithreading & Concurrency Basics",
      "JDBC — Connect Java to MySQL",
      "Spring Boot — REST APIs, Dependency Injection",
      "Maven, Git & GitHub workflow",
      "Capstone Project — Build a full Java backend app",
    ],
    demoTopics: "Java OOP — Classes, Inheritance, live mini-project",
    targetAudience: "Students, freshers & professionals seeking Java jobs",
    duration: "4 Months",
    mode: "Offline / Online",
    instructor: "Rahul Sharma — 8+ years Java & Spring Boot experience",
    batchDate: "5 May 2025",
    seatsLeft: 8,
    testimonials: [
      { name: "Ankit Rawat", role: "Java Developer, TCS Dehradun", text: "Codeware IT's Java course gave me real project experience. I cracked TCS in my first attempt!", rating: 5 },
      { name: "Priya Singh", role: "Backend Intern, Startup Dehradun", text: "The small batch size meant I got personal attention every class. Best institute in Dehradun!", rating: 5 },
      { name: "Vikram Negi", role: "BCA Student, HNB Garhwal", text: "After struggling with Java in college, Codeware IT made it crystal clear. Highly recommend!", rating: 5 },
    ],
  },

  "python-course-dehradun": {
    slug: "python-course-dehradun",
    title: "Python Course in Dehradun",
    metaTitle: "Best Python Course in Dehradun | Codeware IT",
    metaDescription:
      "Best Python training in Dehradun at Codeware IT. Learn Python, Django, data science & automation. Placement support. Book FREE demo today!",
    keywords:
      "python course dehradun, python training dehradun, python institute dehradun, learn python dehradun, best python classes dehradun",
    heroTitle: "Best Python Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "From zero to Python pro — automation, web development & data science. Real projects, small batches, guaranteed results at Dehradun's top coding institute.",
    badge: "🔥 Trending",
    color: "#16a34a",
    icon: "🐍",
    category: "Job Ready",
    syllabus: [
      "Python Basics — Syntax, Variables, Data Types",
      "Control Structures — Loops, Conditions, Functions",
      "Object-Oriented Python — Classes, Inheritance",
      "File Handling, Exception Handling",
      "Libraries — NumPy, Pandas, Matplotlib",
      "Web Scraping with BeautifulSoup & Requests",
      "Django Basics — Models, Views, Templates",
      "REST API with Django REST Framework",
      "Introduction to Machine Learning with scikit-learn",
      "Capstone Project — Build a Python web application",
    ],
    demoTopics: "Python Fundamentals + Build a web scraper live",
    targetAudience: "Students, CBSE/ICSE learners, data enthusiasts & professionals",
    duration: "4 Months",
    mode: "Offline / Online",
    instructor: "Neha Bisht — 6+ years Python & Django development",
    batchDate: "5 May 2025",
    seatsLeft: 7,
    testimonials: [
      { name: "Sonia Rawat", role: "Data Analyst, MNC Dehradun", text: "Codeware IT's Python course is hands-on from day one. Got my data analyst role within 2 months!", rating: 5 },
      { name: "Deepak Semwal", role: "Python Dev, Remote Job", text: "The instructor explains things so clearly. I went from zero to building Django apps!", rating: 5 },
      { name: "Riya Negi", role: "CBSE Class 12 Topper", text: "My board exam Python score jumped to 97/100 after just 1 month at Codeware IT!", rating: 5 },
    ],
  },

  "mern-stack-course-dehradun": {
    slug: "mern-stack-course-dehradun",
    title: "MERN Stack Course in Dehradun",
    metaTitle: "Best MERN Stack Course in Dehradun | Codeware IT",
    metaDescription:
      "Top MERN Stack training in Dehradun. Learn MongoDB, Express, React & Node.js at Codeware IT. Job placement support. Book FREE demo today!",
    keywords:
      "mern stack course dehradun, mern stack training dehradun, mern stack institute dehradun, learn mern stack dehradun, mongodb react nodejs express dehradun",
    heroTitle: "Best MERN Stack Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Build full-stack web apps with MongoDB, Express, React & Node.js. Industry-ready curriculum with real projects & job placement support.",
    badge: "🚀 Job Ready",
    color: "#0ea5e9",
    icon: "⚡",
    category: "Job Ready",
    syllabus: [
      "JavaScript ES6+ — Async/Await, Destructuring, Modules",
      "React.js — Components, Hooks, State Management",
      "React Router & Context API",
      "Node.js — Runtime, Modules, File System",
      "Express.js — REST APIs, Middleware, Error Handling",
      "MongoDB & Mongoose — CRUD, Aggregation, Indexing",
      "Authentication — JWT, bcrypt, Refresh Tokens",
      "Redux Toolkit for State Management",
      "Deployment — Vercel (Frontend) + Railway (Backend)",
      "Capstone MERN Project — E-commerce / Portfolio App",
    ],
    demoTopics: "MERN Stack live — React UI + Node API + MongoDB in 60 min",
    targetAudience: "Web dev enthusiasts, CS graduates, career switchers",
    duration: "5 Months",
    mode: "Offline / Online",
    instructor: "Arjun Thapa — 7+ years MERN Stack & Startup experience",
    batchDate: "5 May 2025",
    seatsLeft: 6,
    testimonials: [
      { name: "Gaurav Bisht", role: "MERN Stack Dev, Infosys", text: "The MERN course at Codeware IT is the real deal. I built 3 live projects and got placed in Infosys!", rating: 5 },
      { name: "Swati Rana", role: "Full Stack Intern, Dehradun Startup", text: "Finally understood how frontend and backend connect. Best MERN Stack institute in Dehradun!", rating: 5 },
      { name: "Rohan Joshi", role: "Freelance Developer", text: "Within 4 months I started taking freelance projects. Codeware IT's curriculum is industry-aligned!", rating: 5 },
    ],
  },

  "nodejs-course-dehradun": {
    slug: "nodejs-course-dehradun",
    title: "Node.js Course in Dehradun",
    metaTitle: "Best Node.js Course in Dehradun | Codeware IT",
    metaDescription:
      "Learn Node.js & backend development in Dehradun at Codeware IT. Build scalable APIs, REST services & get job placement support. Book FREE demo!",
    keywords:
      "nodejs course dehradun, node js training dehradun, node js institute dehradun, learn nodejs dehradun, backend course dehradun nodejs",
    heroTitle: "Best Node.js Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Become a backend expert — build high-performance APIs, real-time apps & microservices with Node.js & Express at Dehradun's top coding institute.",
    badge: "💼 High Demand",
    color: "#84cc16",
    icon: "🟩",
    category: "Job Ready",
    syllabus: [
      "Node.js Internals — Event Loop, Non-blocking I/O",
      "CommonJS & ES Modules in Node.js",
      "Express.js — Routing, Middleware, Controllers",
      "REST API Design Principles & Best Practices",
      "MongoDB with Mongoose — Schema, CRUD, Queries",
      "Authentication — JWT, Sessions, OAuth basics",
      "File Uploads — Multer + Cloudinary integration",
      "WebSockets & Real-time apps with Socket.io",
      "Rate Limiting, CORS, Security Headers",
      "Deployment — Docker basics, Railway, Render, AWS EC2",
    ],
    demoTopics: "Node.js + Express — Build a complete REST API live in 45 min",
    targetAudience: "Frontend devs moving to backend, CS students, professionals",
    duration: "3 Months",
    mode: "Offline / Online",
    instructor: "Arjun Thapa — 7+ years backend & API architecture",
    batchDate: "5 May 2025",
    seatsLeft: 8,
    testimonials: [
      { name: "Harish Panwar", role: "Backend Dev, Dehradun Tech Firm", text: "Node.js at Codeware IT made backend development feel natural. Got a job offer within weeks!", rating: 5 },
      { name: "Monika Devi", role: "API Developer, Startup", text: "The course covers everything from basics to deployment. I now build APIs confidently!", rating: 5 },
      { name: "Sumit Bhatt", role: "BTech CSE, Graphic Era", text: "After this course, my college projects look professional. Highly recommend Codeware IT!", rating: 5 },
    ],
  },

  "full-stack-course-dehradun": {
    slug: "full-stack-course-dehradun",
    title: "Full Stack Developer Course in Dehradun",
    metaTitle: "Best Full Stack Course in Dehradun | Codeware IT",
    metaDescription:
      "Top full stack developer course in Dehradun. Learn React, Node.js, MongoDB & deploy real apps at Codeware IT. Placement support. Book FREE demo!",
    keywords:
      "full stack course dehradun, full stack developer course dehradun, full stack training dehradun, full stack institute dehradun, mern full stack dehradun",
    heroTitle: "Best Full Stack Developer Course",
    heroSubtitle: "in Dehradun",
    heroTagline:
      "Master both frontend and backend — build complete web applications end-to-end. The most comprehensive coding course in Dehradun with guaranteed placement support.",
    badge: "🏆 Most Comprehensive",
    color: "#7c3aed",
    icon: "🔮",
    category: "Job Ready",
    syllabus: [
      "HTML5 & CSS3 — Responsive Design, Flexbox, Grid",
      "JavaScript ES6+ — DOM, Fetch, Async/Await",
      "React.js — Components, Hooks, Redux, Router",
      "Node.js & Express — REST APIs, Middleware",
      "MongoDB & Mongoose — Database Design",
      "Authentication — JWT, bcrypt, Role-based access",
      "Next.js — SSR, SSG, API Routes",
      "Git & GitHub — Version control workflow",
      "Deployment — Vercel, Railway, Netlify, AWS",
      "Interview Prep — DSA basics, Resume building, Mock interviews",
    ],
    demoTopics: "Full stack mini-app — React + Node + MongoDB in one session",
    targetAudience: "Anyone who wants a complete developer career transformation",
    duration: "6 Months",
    mode: "Offline / Online",
    instructor: "Rahul Sharma + Arjun Thapa — Combined 15+ years full-stack experience",
    batchDate: "5 May 2025",
    seatsLeft: 5,
    testimonials: [
      { name: "Aakash Verma", role: "Full Stack Dev, Wipro Dehradun", text: "This 6-month course changed my life. From zero to Wipro full-stack developer — Codeware IT made it happen!", rating: 5 },
      { name: "Divya Rawat", role: "Freelance Full Stack Developer", text: "I now earn ₹60k/month freelancing. Codeware IT's full stack course gave me the complete skillset!", rating: 5 },
      { name: "Karan Negi", role: "Startup Founder, Dehradun", text: "I built my own startup app after this course. The best investment I've made in Dehradun!", rating: 5 },
    ],
  },
}


export default courseData;
